<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "contacts"
 *
 * Auto generated by Extension Builder 2013-07-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'contacts',
	'description' => 'Contact extension to replace tt_address',
	'category' => 'plugin',
	'author' => 'Daniel Lorenz',
	'author_email' => 'ext.contact@extco.de',
	'author_company' => 'extco.de UG (haftungsbeschränkt)',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>